/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as RoomCodeSummaryRouteImport } from './routes/room.$code.summary'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeSummaryRoute = RoomCodeSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => RoomCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/room/$code': typeof RoomCodeRouteWithChildren
  '/room/$code/summary': typeof RoomCodeSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/room/$code': typeof RoomCodeRouteWithChildren
  '/room/$code/summary': typeof RoomCodeSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/room/$code': typeof RoomCodeRouteWithChildren
  '/room/$code/summary': typeof RoomCodeSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/settings'
    | '/room/$code'
    | '/room/$code/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/settings'
    | '/room/$code'
    | '/room/$code/summary'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/settings'
    | '/room/$code'
    | '/room/$code/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  SettingsRoute: typeof SettingsRoute
  RoomCodeRoute: typeof RoomCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code/summary': {
      id: '/room/$code/summary'
      path: '/summary'
      fullPath: '/room/$code/summary'
      preLoaderRoute: typeof RoomCodeSummaryRouteImport
      parentRoute: typeof RoomCodeRoute
    }
  }
}

interface RoomCodeRouteChildren {
  RoomCodeSummaryRoute: typeof RoomCodeSummaryRoute
}

const RoomCodeRouteChildren: RoomCodeRouteChildren = {
  RoomCodeSummaryRoute: RoomCodeSummaryRoute,
}

const RoomCodeRouteWithChildren = RoomCodeRoute._addFileChildren(
  RoomCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  SettingsRoute: SettingsRoute,
  RoomCodeRoute: RoomCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
